name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProjects/train_studentperformancefactors.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    #permission content
    permissions:
      contents: write

    steps:
      #check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      #debug repository
      - name: List files in the repository
        run: ls -R
 
      # Install mlflow
      - name: Install dependencies
        working-directory: ./MLProjects
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run file://$GITHUB_WORKSPACE/MLProjects --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - # Sebelum build, kita perlu artefak modelnya.
      # MLflow menyimpan artefak di dalam mlruns. Mari kita salin dari sana.
      - name: Prepare Artifacts for Docker Build
        run: |
          # Dapatkan path ke artefak dari run terbaru
          mlflow artifacts download --run-id $RUN_ID --dst-path ./artifacts
          
          # Pindahkan artefak ke direktori utama agar Dockerfile bisa menemukannya
          mv ./artifacts/model/model.pkl ./final_model.joblib
          # Asumsi preprocessor juga disimpan sebagai artefak dengan nama 'preprocessor'
          mv ./artifacts/preprocessor/preprocessor.joblib ./Preprocess_pipeline.joblib

      - name: Build and Tag Docker Image
        run: |
          docker build -t smsml .
          docker tag smsml ${{ secrets.DOCKER_HUB_USERNAME }}/smsml:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag smsml ${{ secrets.DOCKER_HUB_USERNAME }}/smsml:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/smsml:latest