name: CI Pipeline Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProjects/train_studentperformancefactors.csv"
  TARGET_VAR: "Exam_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    #permission content
    permissions:
      contents: read
      packages: write

    steps:
      #check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      #debug repository
      - name: List files in the repository
        run: ls -R
 
      # Install mlflow
      - name: Install dependencies
        working-directory: ./MLProjects
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run file://$GITHUB_WORKSPACE/MLProjects --env-manager=local

      - name: Set up Git LFS
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main
 
      # Save models to GitHub Repository
      - name: Save mlruns to repo
        env:
          USERNAME: ${{secrets.USERNAME}}
          EMAIL: ${{secrets.EMAIL}}
        run: |
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin main