name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "./Workflow_CI/MLProjects/Train_studentperformancefactors.csv"
  TARGET_VAR: "Exam_Score"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./Workflow_CI/MLProjects/requirements.txt

      - name: Run mlflow project
        run: |
          mlflow run MLProjects --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "smsml"

      - name: Log in to Docker Hub
        # Menggunakan v3 (versi standar terbaru, karena v5 tidak ada)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          # PERBAIKAN: Tag image 'smsml:latest' (yang dibuat MLflow), BUKAN 'cc'
          docker tag smsml:latest ${{ secrets.DOCKER_HUB_USERNAME }}/smsml:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/smsml:latest
