channels:
- conda-forge
dependencies:
- python=3.13.0
- pip<=24.2
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==6.1.1
  - pyarrow==18.1.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
